package com.ws.sample;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-11-18T11:13:47.238+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://sample.ws.com/", name = "ServiceInterfaceWSPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceInterfaceWSPortType {

    @WebMethod
    @RequestWrapper(localName = "getWSoutput", targetNamespace = "http://sample.ws.com/", className = "com.ws.sample.GetWSoutput")
    @ResponseWrapper(localName = "getWSoutputResponse", targetNamespace = "http://sample.ws.com/", className = "com.ws.sample.GetWSoutputResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ws.sample.OutputResult getWSoutput(
        @WebParam(name = "arg0", targetNamespace = "http://sample.ws.com/")
        com.ws.sample.InputOrder arg0
    );
}
