package com.ws.sample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-11-18T11:13:47.286+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "ServiceInterfaceWS", 
                  wsdlLocation = "file:/C:/Users/nirma/worksapce_neno/zwsdl2java/src/main/java/wsdl/callWS.wsdl",
                  targetNamespace = "http://sample.ws.com/") 
public class ServiceInterfaceWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sample.ws.com/", "ServiceInterfaceWS");
    public final static QName ServiceInterfaceWSPort = new QName("http://sample.ws.com/", "ServiceInterfaceWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/nirma/worksapce_neno/zwsdl2java/src/main/java/wsdl/callWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceInterfaceWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/nirma/worksapce_neno/zwsdl2java/src/main/java/wsdl/callWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceInterfaceWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceInterfaceWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceInterfaceWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceInterfaceWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceInterfaceWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceInterfaceWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServiceInterfaceWSPortType
     */
    @WebEndpoint(name = "ServiceInterfaceWSPort")
    public ServiceInterfaceWSPortType getServiceInterfaceWSPort() {
        return super.getPort(ServiceInterfaceWSPort, ServiceInterfaceWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceInterfaceWSPortType
     */
    @WebEndpoint(name = "ServiceInterfaceWSPort")
    public ServiceInterfaceWSPortType getServiceInterfaceWSPort(WebServiceFeature... features) {
        return super.getPort(ServiceInterfaceWSPort, ServiceInterfaceWSPortType.class, features);
    }

}
